#!/usr/bin/env python3
import sys
from myQt import pencere

pencerem = pencere.myWin()
pencerem.winResize(640, 480).winMove(250, 250).winTitle("Zincirli form")

####
# COMING SOON
###

pencerem.winShow()